from flask_downloader.routes.auth import register_auth_routes
from flask_downloader.routes.dlna import register_dlna_routes
from flask_downloader.routes.downloads import register_download_routes
from flask_downloader.routes.main import register_main_routes
from flask_downloader.routes.radio import register_radio_routes
from flask_downloader.routes.settings import register_settings_routes
from flask_downloader.routes.users import register_user_management_routes


def register_application_routes(app, context):
    register_auth_routes(app, {
        "verify_user_credentials": context["verify_user_credentials"],
        "set_session_user": context["set_session_user"],
        "clear_session_user": context["clear_session_user"],
        "set_ui_flash": context["set_ui_flash"],
        "safe_next_url": context["safe_next_url"],
        "is_authenticated": context["is_authenticated"],
        "get_current_username": context["get_current_username"],
        "update_user_password": context["update_user_password"],
        "get_user_by_username": context["get_user_by_username"],
    })

    register_main_routes(app, {
        "quote": context["quote"],
        "FAVICON_SVG": context["FAVICON_SVG"],
        "render_page": context["render_page"],
        "get_mount_info": context["get_mount_info"],
        "require_authenticated_page": context["require_authenticated_page"],
        "is_valid_http_url": context["is_valid_http_url"],
        "extract_http_urls": context["extract_http_urls"],
        "extract_video_data": context["extract_video_data"],
        "build_result_with_proxy_urls": context["build_result_with_proxy_urls"],
        "get_assignable_dlna_collections_for_current_user": context["get_assignable_dlna_collections_for_current_user"],
        "get_daily_download_dir": context["get_daily_download_dir"],
        "get_yt_dlp_services_state": context["get_yt_dlp_services_state"],
        "INDEX_CONTENT_TEMPLATE": context["INDEX_CONTENT_TEMPLATE"],
        "DOWNLOADS_CONTENT_TEMPLATE": context["DOWNLOADS_CONTENT_TEMPLATE"],
        "JOBS_CONTENT_TEMPLATE": context["JOBS_CONTENT_TEMPLATE"],
        "SERVICES_CONTENT_TEMPLATE": context["SERVICES_CONTENT_TEMPLATE"],
    })

    register_download_routes(app, {
        "require_authenticated_json": context["require_authenticated_json"],
        "create_sse_json_response": context["create_sse_json_response"],
        "resolve_view_scope_username": context["resolve_view_scope_username"],
        "get_users_snapshot": context["get_users_snapshot"],
        "is_admin_authenticated": context["is_admin_authenticated"],
        "get_current_username": context["get_current_username"],
        "get_mount_info": context["get_mount_info"],
        "get_server_files": context["get_server_files"],
        "filter_jobs_for_viewer": context["filter_jobs_for_viewer"],
        "get_jobs_snapshot": context["get_jobs_snapshot"],
        "is_valid_http_url": context["is_valid_http_url"],
        "extract_http_urls": context["extract_http_urls"],
        "extract_video_data": context["extract_video_data"],
        "build_result_with_proxy_urls": context["build_result_with_proxy_urls"],
        "find_format": context["find_format"],
        "choose_best_source": context["choose_best_source"],
        "public_source_download_match_state": context["public_source_download_match_state"],
        "get_source_download_match_state": context["get_source_download_match_state"],
        "get_assignable_dlna_collections_for_current_user": context["get_assignable_dlna_collections_for_current_user"],
        "ensure_share_ready": context["ensure_share_ready"],
        "normalize_storage_kind": context["normalize_storage_kind"],
        "create_job": context["create_job"],
        "build_download_filename": context["build_download_filename"],
        "normalize_requested_download_filename": context["normalize_requested_download_filename"],
        "mark_job_cancel_requested": context["mark_job_cancel_requested"],
        "mark_job_pause_requested": context["mark_job_pause_requested"],
        "resume_job_download": context["resume_job_download"],
        "delete_job": context["delete_job_record"],
        "delete_managed_file": context["delete_managed_download_file"],
        "build_m3u": context["build_m3u"],
        "stream_upstream_response": context["stream_upstream_response"],
        "build_intermediate_download_filename": context["build_intermediate_download_filename"],
        "is_authenticated": context["is_authenticated"],
        "build_managed_relative_path": context["build_managed_relative_path"],
        "parse_managed_relative_path": context["parse_managed_relative_path"],
        "safe_relative_download_path": context["safe_relative_download_path"],
        "resolve_download_path": context["resolve_download_path"],
        "normalize_username": context["normalize_username"],
        "DEFAULT_ADMIN_USERNAME": context["DEFAULT_ADMIN_USERNAME"],
        "can_access_owner": context["can_access_owner"],
        "get_user_storage_root": context["get_user_storage_root"],
    })

    register_user_management_routes(app, {
        "is_admin_authenticated": context["is_admin_authenticated"],
        "wants_json_response": context["wants_json_response"],
        "require_admin_json": context["require_admin_json"],
        "set_ui_flash": context["set_ui_flash"],
        "create_user_account": context["create_user_account"],
        "update_user_password": context["update_user_password"],
        "update_user_account": context["update_user_account"],
        "delete_user_account": context["delete_user_account"],
        "get_settings_page_state": context["get_settings_page_state"],
        "ensure_directory": context["ensure_directory"],
        "get_user_storage_root": context["get_user_storage_root"],
        "normalize_username": context["normalize_username"],
        "get_current_username": context["get_current_username"],
    })

    register_settings_routes(app, {
        "is_admin_authenticated": context["is_admin_authenticated"],
        "wants_json_response": context["wants_json_response"],
        "require_admin_json": context["require_admin_json"],
        "create_sse_json_response": context["create_sse_json_response"],
        "set_ui_flash": context["set_ui_flash"],
        "render_page": context["render_page"],
        "SETTINGS_CONTENT_TEMPLATE": context["SETTINGS_CONTENT_TEMPLATE"],
        "get_settings_page_state": context["get_settings_page_state"],
        "save_app_config": context["save_app_config"],
        "build_updated_storage_config": context["build_updated_storage_config"],
        "get_storage_config_snapshot": context["get_storage_config_snapshot"],
        "build_storage_network_signature": context["build_storage_network_signature"],
        "test_network_storage_config": context["test_network_storage_config"],
        "configure_network_storage_config": context["configure_network_storage_config"],
        "mount_network_storage_config": context["mount_network_storage_config"],
        "unmount_network_storage_config": context["unmount_network_storage_config"],
        "remove_network_storage_config": context["remove_network_storage_config"],
        "ensure_share_ready": context["ensure_share_ready"],
        "sync_dlna_runtime_safe": context["sync_dlna_runtime_safe"],
        "refresh_ffmpeg_update_state": context["refresh_ffmpeg_update_state"],
        "start_maintenance_task": context["start_maintenance_task"],
        "install_or_update_ffmpeg": context["install_or_update_ffmpeg"],
        "refresh_yt_dlp_update_state": context["refresh_yt_dlp_update_state"],
        "update_yt_dlp_package": context["update_yt_dlp_package"],
        "refresh_app_update_state": context["refresh_app_update_state"],
        "update_app_from_github": context["update_app_from_github"],
        "refresh_dlna_package_state": context["refresh_dlna_package_state"],
        "refresh_radio_backend_package_state": context["refresh_radio_backend_package_state"],
        "build_dlna_json_response": context["build_dlna_json_response"],
        "install_or_update_dlna_server": context["install_or_update_dlna_server"],
        "install_or_update_radio_backend": context["install_or_update_radio_backend"],
        "parse_boolean_flag": context["parse_boolean_flag"],
        "set_dlna_service_enabled": context["set_dlna_service_enabled"],
        "restart_dlna_service_now": context["restart_dlna_service_now"],
        "set_radio_backend_enabled": context["set_radio_backend_enabled"],
        "restart_radio_backend_now": context["restart_radio_backend_now"],
        "schedule_flask_service_restart": context["schedule_flask_service_restart"],
        "build_config_export_bundle": context["build_config_export_bundle"],
        "restore_config_bundle": context["restore_config_bundle"],
        "get_current_username": context["get_current_username"],
        "get_user_by_username": context["get_user_by_username"],
        "clear_session_user": context["clear_session_user"],
        "set_session_user": context["set_session_user"],
        "SYSTEMD_SERVICE_NAME": context["SYSTEMD_SERVICE_NAME"],
    })

    register_dlna_routes(app, {
        "is_admin_authenticated": context["is_admin_authenticated"],
        "wants_json_response": context["wants_json_response"],
        "require_admin_json": context["require_admin_json"],
        "create_sse_json_response": context["create_sse_json_response"],
        "set_ui_flash": context["set_ui_flash"],
        "render_page": context["render_page"],
        "DLNA_CONTENT_TEMPLATE": context["DLNA_CONTENT_TEMPLATE"],
        "get_dlna_page_state": context["get_dlna_page_state"],
        "DLNA_SERVICE_NAME": context["DLNA_SERVICE_NAME"],
        "DLNA_ALL_COLLECTION_NAME": context["DLNA_ALL_COLLECTION_NAME"],
        "read_text_log_file_for_browser": context["read_text_log_file_for_browser"],
        "DLNA_LOG_FILE": context["DLNA_LOG_FILE"],
        "DLNA_LOG_BROWSER_MAX_BYTES": context["DLNA_LOG_BROWSER_MAX_BYTES"],
        "build_dlna_collection_library_results": context["build_dlna_collection_library_results"],
        "update_dlna_general_settings": context["update_dlna_general_settings"],
        "build_dlna_json_response": context["build_dlna_json_response"],
        "refresh_dlna_package_state": context["refresh_dlna_package_state"],
        "sync_dlna_runtime_safe": context["sync_dlna_runtime_safe"],
        "start_maintenance_task": context["start_maintenance_task"],
        "install_or_update_dlna_server": context["install_or_update_dlna_server"],
        "parse_boolean_flag": context["parse_boolean_flag"],
        "set_dlna_service_enabled": context["set_dlna_service_enabled"],
        "restart_dlna_service_now": context["restart_dlna_service_now"],
        "sync_dlna_runtime": context["sync_dlna_runtime"],
        "create_dlna_collection": context["create_dlna_collection"],
        "update_dlna_collection": context["update_dlna_collection"],
        "delete_dlna_collection": context["delete_dlna_collection"],
        "create_dlna_client": context["create_dlna_client"],
        "update_dlna_client": context["update_dlna_client"],
        "delete_dlna_client": context["delete_dlna_client"],
        "create_dlna_media_rule": context["create_dlna_media_rule"],
        "update_dlna_media_rule": context["update_dlna_media_rule"],
        "bulk_assign_dlna_collection_items": context["bulk_assign_dlna_collection_items"],
        "delete_dlna_media_rule": context["delete_dlna_media_rule"],
    })

    register_radio_routes(app, {
        "require_authenticated_page": context["require_authenticated_page"],
        "require_authenticated_json": context["require_authenticated_json"],
        "is_admin_authenticated": context["is_admin_authenticated"],
        "create_sse_json_response": context["create_sse_json_response"],
        "render_page": context["render_page"],
        "set_ui_flash": context["set_ui_flash"],
        "resolve_view_scope_username": context["resolve_view_scope_username"],
        "get_current_username": context["get_current_username"],
        "RADIO_CONTENT_TEMPLATE": context["RADIO_CONTENT_TEMPLATE"],
        "get_radio_page_state": context["get_radio_page_state"],
        "create_radio_station": context["create_radio_station"],
        "update_radio_station": context["update_radio_station"],
        "delete_radio_station": context["delete_radio_station"],
        "update_radio_global_settings": context["update_radio_global_settings"],
        "add_radio_library_paths": context["add_radio_library_paths"],
        "bulk_save_radio_library": context["bulk_save_radio_library"],
        "update_radio_library_item": context["update_radio_library_item"],
        "remove_radio_library_item": context["remove_radio_library_item"],
        "store_uploaded_radio_audio": context["store_uploaded_radio_audio"],
        "store_uploaded_radio_audio_batch": context["store_uploaded_radio_audio_batch"],
        "start_maintenance_task": context["start_maintenance_task"],
        "refresh_radio_backend_package_state": context["refresh_radio_backend_package_state"],
        "install_or_update_radio_backend": context["install_or_update_radio_backend"],
        "set_radio_backend_enabled": context["set_radio_backend_enabled"],
        "restart_radio_backend_now": context["restart_radio_backend_now"],
        "control_radio_station": context["control_radio_station"],
        "queue_radio_station_track": context["queue_radio_station_track"],
        "read_radio_log_file_for_browser": context["read_radio_log_file_for_browser"],
        "get_radio_backend_log_file": context["get_radio_backend_log_file"],
        "get_radio_station_log_file": context["get_radio_station_log_file"],
        "RADIO_LOG_BROWSER_MAX_BYTES": context["RADIO_LOG_BROWSER_MAX_BYTES"],
    })


def start_background_schedulers(context):
    context["start_ffmpeg_scheduler_once"]()
    context["start_yt_dlp_scheduler_once"]()
    context["start_dlna_scheduler_once"]()
    if context.get("start_radio_package_scheduler_once"):
        context["start_radio_package_scheduler_once"]()
    if context.get("start_dlna_autoheal_scheduler_once"):
        context["start_dlna_autoheal_scheduler_once"]()
    if context.get("start_radio_metadata_scheduler_once"):
        context["start_radio_metadata_scheduler_once"]()


__all__ = [
    "register_application_routes",
    "start_background_schedulers",
]
